# Generated by Django 6.0.5 on 2026-05-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('contact_name', models.CharField(max_length=150, verbose_name='Nom du contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('vehicle_count', models.PositiveSmallIntegerField(verbose_name='Nombre de véhicules')),
                ('service_type', models.CharField(choices=[('contrat_flotte', "Contrat d'entretien de flotte"), ('reparation', 'Réparation / Dépannage'), ('lavage', 'Lavage & Nettoyage'), ('pieces', 'Vente de pièces'), ('autre', 'Autre')], max_length=30, verbose_name='Service souhaité')),
                ('message', models.TextField(blank=True, verbose_name='Message complémentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
