# Generated by Django 6.0 on 2026-05-25 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='vehicle_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de véhicules'),
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence')),
                ('company_name', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('vehicle_count', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de véhicules')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='TVA (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('terms', models.TextField(blank=True, verbose_name='Conditions de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('quote_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='quotes.quoterequest', verbose_name='Demande source')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevisLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(default='forfait', max_length=30, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
            },
        ),
    ]
