# Generated by Django 6.0.5 on 2026-05-12 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Immatriculation')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('vehicle_type', models.CharField(choices=[('vl', 'Véhicule léger'), ('vu', 'Utilitaire'), ('pl', 'Poids lourd'), ('engin', 'Engin')], max_length=10, verbose_name='Type')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Kilométrage actuel')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'intervention")),
                ('description', models.TextField(verbose_name='Travaux réalisés')),
                ('mileage_at_service', models.PositiveIntegerField(verbose_name="Kilométrage à l'intervention")),
                ('cost', models.PositiveIntegerField(verbose_name='Coût (FCFA)')),
                ('technician', models.CharField(blank=True, max_length=100, verbose_name='Technicien')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date'],
            },
        ),
    ]
