# Generated by Django 6.0.5 on 2026-05-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('maintenance', 'Entretien courant'), ('freinage', 'Freinage'), ('suspension', 'Suspension'), ('electricite', 'Électricité / Électronique'), ('tolerie', 'Tôlerie & Peinture'), ('motorisation', 'Motorisation'), ('pneumatiques', 'Pneumatiques'), ('forfaits', 'Forfaits flotte'), ('lavage', 'Lavage & Nettoyage')], max_length=50, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_light_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix min VL (FCFA)')),
                ('price_light_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix max VL (FCFA)')),
                ('price_heavy_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix min PL (FCFA)')),
                ('price_heavy_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix max PL (FCFA)')),
                ('price_on_quote', models.BooleanField(default=False, verbose_name='Sur devis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
